### PR TITLE
Add french translations and small fixes

### LINKED ISSUE #77: Translate key text in app to French
After we have a i18n available, then we'll want to be able to translate key parts of the app. If you speak French and would feel comfortable translating the key text, that would be great!

This is what we need translated: 

* tab titles
  * `Event Details`
  * `Speakers`
  * `Talks`
  * `Recordings`
  * `FAQs/Frequently Asked Questions`
* Calendar Button text: `Save the {date} session`
* Second button text:
  * `Sign up for updates`
  * `Join the slack group`
* Button on talks page text:  `Show times in EDT` and `Show times in Local`

### PR DESCRIPTION
**Pull request by bpvcode**
#### Describe your changes
* [x] Add `./translactions/fr.json` with french translations;
* [x] Fix `./translactions/de.json` - (Add commas for JSON structure)
* [x] Fix lint issues - (Remove unused import and variable)

#### Link to issue this resolves
The issue to resolve: #77 

Reviewer: @brittanyjoiner15  
Assignee: @bpvcode

### CODE REVIEW

File: src/components/MainPage.jsx [hunk 1]
```diff
@@ -15,7 +15,6 @@ import RecordingsPanel from "./panels/RecordingsPanel";
 import FAQsPanel from "./panels/FAQsPanel";
 import { Routes, Route } from "react-router-dom";
 import history from "../utilities/history";
-import { getColorTheme } from "../utilities/colors";
```
Comment (brittanyjoiner15) [inline src/components/MainPage.jsx:18]: Good catch, thanks!

File: src/components/panels/FAQsPanel.jsx [hunk 2]
```diff
@@ -57,7 +57,7 @@ const FaqAccordionRow = ({ question, detail, answer }) => {
 }
 
 export default function FAQsPanel() {
-  const [isXs, isS, isM] = [useIsXs(), useIsS(), useIsM()];
+  const [isXs, isS] = [useIsXs(), useIsS(), useIsM()];
```
Comment (brittanyjoiner15) [inline src/components/panels/FAQsPanel.jsx:60]: Good catch!

File: translations/de.json [hunk 3]
```diff
@@ -1,13 +1,13 @@
...
-  "eventDetails": "Veranstaltungsdetails"
-  "speakers": "Vortragende"
-  "talks": "Vorträge"
-  "recordings": "Aufzeichnungen"
-  "faq": "FAQ/häufig gestellte Fragen"
-  "saveDate": "Folgende Sitzung speichern: {date}"
-  "signUp": "Einloggen für Updates"
-  "joinSlack": "Trete der Slack Gruppe bei"
-  "showDatesEDT": "zeige Uhrzeiten in Zeitzone EDT an"
+  "eventDetails": "Veranstaltungsdetails",
```
Comment (brittanyjoiner15) [inline translations/de.json:2]: thanks for catching this - was so busy catching up on PRs my reviews are slipping! that would have been problematic down the road, so thanks for fixing!

File: translations/fr.json [hunk 4]
```diff
@@ -0,0 +1,19 @@
+{
+    "Event Details": "Détails de l'évènement",
```
Comment (brittanyjoiner15) [inline translations/fr.json]: @bpvcode can we match these keys to be the same as the german ones? I need to check the Spanish ones, but ideally, all of these will be consistent across all the languages so that the token is universal and just searches for the right language. So if you can match these keys to be 
`eventDetaills` instead of `Event Details`, etc that would be awesome!!

**Review by brittanyjoiner15 — CHANGES_REQUESTED** [review]
Few requested changes, but should be quick! Thanks for the proactiveness with the other things you found!

File: src/components/MainPage.jsx (hunk 1 above)
Comment (bpvcode) [reply src/components/MainPage.jsx:18]: You're welcome :)

File: translations/fr.json (hunk 4 above)
Comment (bpvcode) [reply translations/fr.json]: Oh sorry about this, my mistake... I was clearly distracted.
I will do the changes right now :)
Thanks for the feedback

**Comment by bpvcode** [comment]
Hello @brittanyjoiner15 ,

Just to ask if you are waiting on me to make more changes to this, or if is ok for you the changes that i did after your review.

Thanks :)

**Review by brittanyjoiner15 — APPROVED** [review]
These changes look good! Thank you so much for your contribution!

**Comment by brittanyjoiner15** [comment]
@bpvcode looks good! merging now!
